#
# Get all execution environments
#
#

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX faas: <http://www.semantic-faas.com/ontology#>

SELECT  DISTINCT ?subject
WHERE {
  ?subject rdf:type owl:NamedIndividual .
  ?subject rdf:type faas:HostedServerlessExecutionEnvironment .
}
