#
# Get a suitable execution environment for CovidTracker
#
#

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX locn: <http://www.w3.org/ns/locn#>

PREFIX faas: <http://www.semantic-faas.com/ontology#>

SELECT  DISTINCT ?subject
WHERE {
  VALUES ?targetApplication { faas:CovidTracker }

  #### Filter for Geo Restrictions
  ?targetApplication faas:requirements ?geoRequirement .
  ?geoRequirement rdf:type faas:GeographicalRequirement .
  ?geoRequirement wdt:P361 ?desiredLocation .

  ?subject rdf:type owl:NamedIndividual .
  ?subject rdf:type faas:ServerlessExecutionEnvironment .
  ?subject faas:datacenter ?datacenter .

  # at least one datacenter respects the geo restriction
  ?datacenter locn:addressArea ?addressArea .
  # P361 = part of
  ?addressArea wdt:P361 ?desiredLocation .

  #### Filter for ExecutionTime Restrictions

  ?targetApplication faas:requirements ?executionTIme .
  ?executionTIme rdf:type faas:ExecutionTimeRequirement .
  ?executionTIme faas:maxTimeAllowed ?maxTimeAllowed .

  ?subject faas:maxTimeAllowed ?SubjectMaxTimeAllowed .

  FILTER (xsd:integer(?SubjectMaxTimeAllowed) >= xsd:integer(?maxTimeAllowed))
}
